import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {AuthProvider} from "@/context/AuthContext";
import { StudentProvider } from "@/context/StudentContext";
import { MedicineProvider } from "@/context/MedicinesContext";
import { KunjunganUksProvider } from "@/context/KunjunganUksContext";
import { RiwayatKunjunganUksProvider } from '@/context/RiwayatKunjunganUksContext';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Medcheck",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <AuthProvider>
          <StudentProvider>
            <MedicineProvider>
              <KunjunganUksProvider>
                <RiwayatKunjunganUksProvider>
                  {children}
                </RiwayatKunjunganUksProvider>
                </KunjunganUksProvider>
            </MedicineProvider>
          </StudentProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
